//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankInfo()
        {
            this.TripBankInfo = new HashSet<TripBankInfo>();
        }
    
        public int IdBankInfo { get; set; }
        public string BankAddress { get; set; }
        public string BankPostalCode { get; set; }
        public Nullable<int> BankCity { get; set; }
        public string BankProvince { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string SwiftCode { get; set; }
        public Nullable<int> IdBank { get; set; }
        public Nullable<int> TransitNumber { get; set; }
        public string Customer { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripBankInfo> TripBankInfo { get; set; }
    }
}
