//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigApp
    {
        public int IdConfigApp { get; set; }
        public string NameApp { get; set; }
        public string AccountPOP3 { get; set; }
        public string PortPOP3 { get; set; }
        public string AccountSMTP { get; set; }
        public string PortSMTP { get; set; }
        public string account { get; set; }
        public string PasswordAccount { get; set; }
    }
}
