//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Destination()
        {
            this.TransferEstimate = new HashSet<TransferEstimate>();
        }
    
        public int IdDestination { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> IdTypeDestination { get; set; }
        public Nullable<int> IdSalesContact { get; set; }
        public Nullable<int> IdCity { get; set; }
    
        public virtual SalesContact SalesContact { get; set; }
        public virtual TypeDestination TypeDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferEstimate> TransferEstimate { get; set; }
        public virtual PriceCities PriceCities { get; set; }
    }
}
