//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationSalesContact
    {
        public int IdSalesConttDest { get; set; }
        public Nullable<int> IdDestination { get; set; }
        public Nullable<int> IdSalesContact { get; set; }
    }
}
