//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastIPReservation
    {
        public int IdIP { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DateReservation { get; set; }
    }
}
