//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationRequest
    {
        public int IdReservationRequest { get; set; }
        public string NamePD { get; set; }
        public string AddressPD { get; set; }
        public string PostalCodePD { get; set; }
        public string PhonePD { get; set; }
        public string MobilePD { get; set; }
        public Nullable<int> IdCityPD { get; set; }
        public Nullable<int> IdTypeDestinationPD { get; set; }
        public Nullable<int> IdPassenger { get; set; }
        public Nullable<int> IdTransferEst { get; set; }
    }
}
