//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusPayment()
        {
            this.TransferEstimate = new HashSet<TransferEstimate>();
        }
    
        public int IdStatusPayment { get; set; }
        public string DescStatusPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferEstimate> TransferEstimate { get; set; }
    }
}
