//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferSend
    {
        public int IdTransferSend { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<int> IdTransEst { get; set; }
        public Nullable<int> IdAprove { get; set; }
        public string SmallMessage { get; set; }
        public string Note { get; set; }
        public string NameUser { get; set; }
    }
}
