//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferEstimate
    {
        public int IdTransEst { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> DateFligh { get; set; }
        public string TimeFligh { get; set; }
        public string TimePiDo { get; set; }
        public Nullable<int> IdMetingPoint { get; set; }
        public Nullable<int> QtyPassenger { get; set; }
        public Nullable<int> QtyMalaGr { get; set; }
        public Nullable<int> QtyMalaPq { get; set; }
        public Nullable<int> CityFromId { get; set; }
        public Nullable<int> CityToId { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<System.DateTime> DateTransEst { get; set; }
        public Nullable<System.DateTime> DateAprove { get; set; }
        public string NamePassenger { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdAprove { get; set; }
        public Nullable<int> IdTypeDestination { get; set; }
        public Nullable<int> IdDestination { get; set; }
        public Nullable<int> IdSales { get; set; }
        public Nullable<int> IdTypeTransfer { get; set; }
        public Nullable<int> IdTypePayment { get; set; }
        public Nullable<int> IdStatusPayment { get; set; }
        public string TypeVisa { get; set; }
        public Nullable<int> QtyPassengerKids { get; set; }
        public Nullable<System.DateTime> DateRequestEstimate { get; set; }
        public Nullable<int> IdPassenger { get; set; }
    
        public virtual MetingPoint MetingPoint { get; set; }
        public virtual SalesContact SalesContact { get; set; }
        public virtual StatusPayment StatusPayment { get; set; }
        public virtual TransferAprove TransferAprove { get; set; }
        public virtual TypeDestination TypeDestination { get; set; }
        public virtual TypePayment TypePayment { get; set; }
        public virtual TypeTransfer TypeTransfer { get; set; }
        public virtual PriceCities PriceCitiesFrom { get; set; }
        public virtual PriceCities PriceCitiesTo { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
