//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripBankInfo
    {
        public int IdTripBankInfo { get; set; }
        public Nullable<int> IdTripInfo { get; set; }
        public Nullable<int> IdBankInfo { get; set; }
    
        public virtual TripInfo TripInfo { get; set; }
        public virtual BankInfo BankInfo { get; set; }
    }
}
