//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripInfo()
        {
            this.TripBankInfo = new HashSet<TripBankInfo>();
        }
    
        public int IdTripInfo { get; set; }
        public string TripName { get; set; }
        public string TripAddress { get; set; }
        public string TripPostalCode { get; set; }
        public Nullable<int> TripCity { get; set; }
        public string TripProvince { get; set; }
    
        public virtual PriceCities PriceCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripBankInfo> TripBankInfo { get; set; }
    }
}
