//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWebTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class atripservicesEntities : DbContext
    {
        public atripservicesEntities()
            : base("name=atripservicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<TypeTransfer> TypeTransfer { get; set; }
        public virtual DbSet<TypeDestination> TypeDestination { get; set; }
        public virtual DbSet<SalesContact> SalesContact { get; set; }
        public virtual DbSet<SalesSource> SalesSource { get; set; }
        public virtual DbSet<StatusPayment> StatusPayment { get; set; }
        public virtual DbSet<TransferAprove> TransferAprove { get; set; }
        public virtual DbSet<TypePayment> TypePayment { get; set; }
        public virtual DbSet<MetingPoint> MetingPoint { get; set; }
        public virtual DbSet<TransferEstimate> TransferEstimate { get; set; }
        public virtual DbSet<ACCESS> ACCESS { get; set; }
        public virtual DbSet<PriceCities> PriceCities { get; set; }
        public virtual DbSet<Destination> Destination { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<TransferSend> TransferSend { get; set; }
        public virtual DbSet<ConfigApp> ConfigApp { get; set; }
        public virtual DbSet<TypeVisa> TypeVisa { get; set; }
        public virtual DbSet<DestinationSalesContact> DestinationSalesContact { get; set; }
        public virtual DbSet<ReservationRequest> ReservationRequest { get; set; }
        public virtual DbSet<LastIPReservation> LastIPReservation { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<TripBankInfo> TripBankInfo { get; set; }
        public virtual DbSet<TripInfo> TripInfo { get; set; }
        public virtual DbSet<BankInfo> BankInfo { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
