//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInvoiceApp.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESS
    {
        public int IdLogin { get; set; }
        public string Email { get; set; }
        public string UserLog { get; set; }
        public string UserLogin { get; set; }
        public string Password { get; set; }
        public string Active { get; set; }
        public string Profile { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
    }
}
