//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebInvoiceApp.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Issuer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issuer()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int IdIssuer { get; set; }
        [Required(ErrorMessage = "Issuer Name is required!", AllowEmptyStrings = false)]
        [Display(Name = "Issuer Name")]
        [StringLength(100, MinimumLength = 4)]
        public string NameIssuer { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Fone { get; set; }
        [Required]
        [Display(Name = "Email")]
        [RegularExpression(@"^\S*$", ErrorMessage = "Email Address cannot have white spaces")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        [StringLength(150, MinimumLength = 4)]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
