//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInvoiceApp.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string TypeProducts { get; set; }
        public string DescriptionProd { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalProd { get; set; }
        public Nullable<decimal> TaxProd { get; set; }
        public Nullable<decimal> LineTotalProd { get; set; }
        public Nullable<int> NumInvoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
