//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInvoiceApp.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeTaxServ
    {
        public int IdTypeTaxServ { get; set; }
        public string DescTypeTaxServ { get; set; }
        public Nullable<decimal> TaxServ { get; set; }
        public Nullable<int> NumInvoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
